// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbtJbo0vpR-Isy1TE5-tgQ0OPu_Oau5-Y',
    appId: '1:505634503909:web:aa845723f77ffbc31d280c',
    messagingSenderId: '505634503909',
    projectId: 'solvequery-2024',
    authDomain: 'solvequery-2024.firebaseapp.com',
    storageBucket: 'solvequery-2024.appspot.com',
    measurementId: 'G-9QKNSNDX7Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9HsFFoQePgYI4irkIdJoQ0zoZsV_xfaU',
    appId: '1:505634503909:android:745ec8044332a6f71d280c',
    messagingSenderId: '505634503909',
    projectId: 'solvequery-2024',
    storageBucket: 'solvequery-2024.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBagLIBaBmfG7Sa2gxUEAz3GyxywThfeKQ',
    appId: '1:505634503909:ios:186d9a089a3d4baf1d280c',
    messagingSenderId: '505634503909',
    projectId: 'solvequery-2024',
    storageBucket: 'solvequery-2024.appspot.com',
    androidClientId: '505634503909-ph72hhpr9t7p2uaom6u8479msfjue4p2.apps.googleusercontent.com',
    iosClientId: '505634503909-perlb8p1r9tagtbet8pvmm5mif7jttnj.apps.googleusercontent.com',
    iosBundleId: 'com.example.sq',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBagLIBaBmfG7Sa2gxUEAz3GyxywThfeKQ',
    appId: '1:505634503909:ios:16a610cfc5b66a5b1d280c',
    messagingSenderId: '505634503909',
    projectId: 'solvequery-2024',
    storageBucket: 'solvequery-2024.appspot.com',
    androidClientId: '505634503909-ph72hhpr9t7p2uaom6u8479msfjue4p2.apps.googleusercontent.com',
    iosClientId: '505634503909-dsegasvpb0c5titb6sdg4vvjsple4glr.apps.googleusercontent.com',
    iosBundleId: 'com.example.sq.RunnerTests',
  );
}
